BaseUrl= "https://turq.io/"
LanguageCode= "en-US"
Title= "Turq"
theme = "hugo-cards"
paginate = 6
themesDir = "./themes"

[params]
  builtBy = "bool"
  defaultImage = "turq_logo.PNG"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"

[menu]
    
  [[menu.main]]
    identifier = "competitions"
    name = "competitions"
    url = "/competition/"
    weight = -100

