BaseUrl= "https://turq.netlify.app/"
LanguageCode= "en-US"
Title= "Turq"
paginate = 5
Copyright = "All rights reserved - 2020"
canonifyurls = true

[params]
  description = "Turq provides a platform to host competitions to create Citizen Legislation."
  metadescription = "Turq - Citizen Legislation"
  cover = "images/cover.jpg"
  logo = "images/turq_logo.PNG"
  hideHUGOSupport = false
  
  hjsStyle = "default"

[menu]
    
  [[menu.main]]
    identifier = "competitions"
    name = "competitions"
    url = "/competition/"
    weight = -100

